### ISSUE TITLE
Form Fields

### ISSUE THREAD

**Issue by Dude9177** [jbrad/bootstrap-ios7#4]
Form fields are not in flat iOS7 Design.

Flat Design for Input Fields, Switch for Checkboxes.

But nevertheless ... great work man :)

**Comment by jbrad** [comment]
Thanks! I will take a look at this an will fix in the next release.

**Comment by jbrad** [comment]
I'm planning on including the flat design for input fields, but not adding the switches for checkboxes. I might make another repo that adds that styling for switches later on, but not planning on adding it to master. If you want to add it yourself, check out [this codepen](http://codepen.io/BandarRaffah/pen/ibwje).

**Comment by jbrad** [comment]
I thought about this and I'm not planning on making any changes master for this at this time. If this is something you want to do, please feel free to clone this project and add it yourself.
