### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by pattyland** [jbrad/bootstrap-ios7#5]
Looks awesome! Do you think about putting it on a cdn like http://www.bootstrapcdn.com/ or http://cdnjs.com/?

**Comment by jbrad** [comment]
Thanks! I have thought about trying to get it on a CDN site like bootstrapcdn.com

**Comment by jbrad** [comment]
I just sent them a tweet to hopefully start a conversation https://twitter.com/jason_bradley/status/417709138605375488

**Comment by jbrad** [comment]
I am continuing to pursue this and have contacted the owner of [Bootswatch](http://bootswatch.com/) to see if I could get this theme added. If not, I might look to add it to [cdnjs](http://cdnjs.com/).

**Comment by jbrad** [comment]
It doesn't seem this is possible at this time, but I will reopen this issue if I am able to do so in the future.
