### ISSUE TITLE
Does theme have to be tightly coupled to bootstrap?

### ISSUE THREAD

**Issue by whitneyland** [jbrad/bootstrap-ios7#6]
I'm not a css expert, but is it possible to develop the theme using only bootstrap-theme.css, rather than requiring modification of the base bootstrap file?

**Comment by jbrad** [comment]
It was not totally possible to make this theme without changing some of the core files. There were some issues with Bootstrap with their mixins and it seems that they may have been fixed with the latest release. I plan on updating the project to Bootstrap 3.1.0 as soon as I have time.
