### ISSUE TITLE
Icon buttons don't work

### ISSUE THREAD

**Issue by whitneyland** [jbrad/bootstrap-ios7#7]
Any reason this should not work with your theme?  (star does not appear, even after adding glyphs to the font folder)

<button type="button" class="btn">
            <span class="glyphicon glyphicon-star"></span> Test Button
</button>

**Comment by jbrad** [comment]
The do work with the ionicons as you can see in this [example](http://jasonbradley.me/bootstrap-ios7/components/#ionicons-examples)
